### ISSUE TITLE
Create upstream pr from controlled vocabulary

### ISSUE THREAD

**Issue by davidschober** [nulib/donut#176]
### Description
Determine what controlled vocab updates implemented locally would benefit or be appropriate for Hyrax core.  At a minimum, see if Authority Select works with multiple items in Hyrax core, and fix that.  Up for debate whether controlled vocab mixed with Authority Select is a generic enough use case for users outside of Northwestern.

### Done Looks Like
- Make a decision whether local controlled vocab / authority select updates are necessary for Hyrax core.
- If yes, do the work.

### Tasks
- [ ] - Decide whether local controlled vocab / authority select updates are necessary for Hyrax core.
- [ ] If so, update Hyrax and submit a PR.
- [ ] Merge PR back into Donut and check everything still works (create a new ticket for this).

**Comment by adamjarling** [comment]
Decided to abandon this, as the NU use case may not be universal.
